### PR TITLE
Set minimum OS X version to 10.9

### PR DESCRIPTION
**Pull request by tylerlong**
Fix https://github.com/evermeer/EVReflection/issues/117

### CODE REVIEW

**Comment by evermeer** [comment]
Thanks!

**Comment by tylerlong** [comment]
By the way, the minimum tvOS version is set to 9.1. Is there any reason not to start with 9.0 instead?

**Comment by tylerlong** [comment]
@evermeer in order for Carthage to pick the latest update, you need to create a new tag and push it to GitHub. For example: `git tag 2.45.1`

**Comment by evermeer** [comment]
@tylerlong... working on that... Was first looking why I had set tvOS to 9.1.. The CocoaPods podspec I have defined it as 9.0. I don't remember any reason why I set it to 9.1

**Comment by tylerlong** [comment]
It's OK, take your time 👍  

Thank you for this wonderful project!

**Pull request merged**
