### PR TITLE
Typo in timezone part of RFC3339/ISO8601 date format

### PR DESCRIPTION
**Pull request by readefries**
Fixed the major typo I mentioned in the other PR...

### CODE REVIEW

**Comment by readefries** [comment]
Could you also update the version, podspec and create a tag for it?

Thanks!

**Comment by evermeer** [comment]
Sure, will do that now. will be there in 10 minutes...

**Comment by evermeer** [comment]
There now is a version 2.15.3

**Comment by readefries** [comment]
Great, thanks!

**Pull request merged**
