### PR TITLE
cleanupKey() performance improvements

### PR DESCRIPTION
**Pull request by rafcabezas**
Some improvements for this issue: https://github.com/evermeer/EVReflection/issues/62
Please check my implementation of the cache to make sure I'm not missing anything. It's a very simple implementation.

Thanks!

### CODE REVIEW

**Comment by rafcabezas** [comment]
I was having trouble running the unittests, but got them working now, and I see some failing. So I have to take another look at the caching..

**Comment by evermeer** [comment]
Ok, If you need any help, then just let me know.

**Comment by rafcabezas** [comment]
Been making updates. My main problem ATM is that the cache has to have class-level visibility; but EVReflection methods are all class methods. Since the cache needs to be reset for each use, it creates potential thread-safety issues. So this solution won't work. I need to make the cache so it doesn't need to be reset; or rewrite cleanupKey so it's more cache-friendly.

**Comment by rafcabezas** [comment]
Making good progress doing things a bit different. Pull request coming soon.

**Comment by evermeer** [comment]
Don't rush 😀

**Comment by rafcabezas** [comment]
No worries :)
I just issued a new pull request (https://github.com/evermeer/EVReflection/pull/79).
Let me know what you think!

**Pull request closed without merging**
