### PR TITLE
Add toJsonString() to Array

### PR DESCRIPTION
**Pull request by rafcabezas**
As discussed here: evermeer#40

### CODE REVIEW

**Comment by evermeer** [comment]
Cool! You even used the suggested code 😊

**Comment by rafcabezas** [comment]
Of course :) just simplified it a tiny bit. Thank you!

**Comment by evermeer** [comment]
I see. I thought you had to enumerate when accessing the array in an extension. 
Don't you love the Swift  .filter .map and .reduce functions?

**Comment by rafcabezas** [comment]
Yes!, they're awesome. I was actually working on a simplified solution similar to yours, but in mine I was using reduce instead of joinWithSeparator. For some reason I was thinking joinWithSeparator would add a comma at the end XD.

**Comment by evermeer** [comment]
I just pushed a new version 2.15.4 for use with cocoapods

**Comment by rafcabezas** [comment]
:rocket: :+1:

**Comment by rafcabezas** [comment]
BTW, noticed you removed the extraneous colon `:` from the description. I copy+pasted that description from NSObject's toJsonString(), in case you want to fix that one too.

**Pull request merged**
