### PR TITLE
Performance optimizations to cleanupKey() (For https://github.com/evermeer/EVReflection/issues/62)

### PR DESCRIPTION
**Pull request by rafcabezas**
Also added another performance test to the EVReflectionTestApp
And relaxed swift lint (feel free to not take this change)

### CODE REVIEW

**Comment by evermeer** [comment]
I will have a look at it now.

**Comment by evermeer** [comment]
The test testTypeJson2AllNumeric fails in cleaning up the json key that conatains an astrix.

https://github.com/evermeer/EVReflection/blob/7bc8b3a30f36a2b7f8af66e90a0fc0fef4fd91e9/EVReflection/EVReflectionTests/EVReflectionJsonTests.swift#L189-L189

**Comment by evermeer** [comment]
Strange... It's a cool optimisation, but apperently it does not work.
This code already fails:

```
        let illegalCharacterSet = NSCharacterSet(charactersInString: " -&%#@!$^*()<>?.,:;").invertedSet
        let output = "test*this".componentsSeparatedByCharactersInSet(illegalCharacterSet).joinWithSeparator("_")
        XCTAssertEqual(output, "test_this")

```

**Comment by evermeer** [comment]
Ah. found it... You do not have to take the invertedSet

**Comment by evermeer** [comment]
This has now been pushed as version 2.28.0
Thanks for the improvements. I really liked this improvement:
`.componentsSeparatedByCharactersInSet(illegalCharacterSet).joinWithSeparator("_")`

**Comment by rafcabezas** [comment]
Cool, thanks!. And sorry I missed that! :O 
The caching actually improves performance by close to 50% :)

**Comment by evermeer** [comment]
I think I will add another caching mechanism later this week. The toDictionary function is often called only to get the structure of an object. That structure could be cashed in those cases. Especially when going from json to objects you only need to call that once per object type. Now it's called for every object.

**Comment by rafcabezas** [comment]
Yes, that sounds like a good thing to cache as well. I'll run some more profiling later, to find more bottlenecks, and let you know what I find.

**Pull request merged**
