### PR TITLE
The dateformatter should use RFC3339/ISO8601 as default format

### PR DESCRIPTION
**Pull request by readefries**

### CODE REVIEW

**Comment by evermeer** [comment]
Thanks! you made it easy for me.

**Comment by evermeer** [comment]
Why the ZZZZZ? When running the unit tests, I get this in the output:
"dates" : [
    "2016-01-19T09:37:30.030ZZZZZ",
    "2016-01-19T09:37:30.030ZZZZZ"
  ]

**Comment by readefries** [comment]
That should be ZZZZ, and indicated the Timezone offset from UTC.

How do you run the test btw? I couldn't get them to work on Xcode 7.2. Do you use any plugins for that?

**Comment by evermeer** [comment]
I always start them from the tests navigater (command 5). 
Indeed running them from the file directly does not work for me too.

**Pull request merged**
