### PR TITLE
Support multiple bundle identifiers

### PR DESCRIPTION
**Pull request by Dimillian**

### CODE REVIEW

**Comment by Dimillian** [comment]
What do you think? It solves the problem in my case, and work toward: https://github.com/evermeer/EVReflection/issues/25

**Comment by evermeer** [comment]
This is indeed a quick fix for the problem. It's not ideal yet. You can't have the same class name in 2 bundles. But It's better than the current version. 

I am still thinking of solving #25 the way it should. In almost all cases I should be able to defer the bundle from the class that is used in the function that is called initially. So I will leave issue #25 open, but for now I will merge this pull request. But let me first do some tests with it...

**Comment by Dimillian** [comment]
Yes this is the issue, in my case it's not. And I believe in most of the case it shouldn't be a problem. But indeed, dirty fix.

**Comment by evermeer** [comment]
This now has been pushed to GitHub and Cocoapods as version 2.21.0

**Pull request merged**
