### PR TITLE
Remove required from EVObject's convenience initializers

### PR DESCRIPTION
**Pull request by JRG-Developer**
Since `EVObject`'s convenience initializers are marked as `required`, it's _very_ difficult to add a custom initializer in a subclass. However, IMHO, there isn't any good reason for the convenience initializers to be required at all.

This PR removes the `required` attributes from the convenience initializers.

This way, subclasses only need to override a single initializer, `init`, and you can then add your own custom initializers to them. Subclasses also get all of `EVObject`'s convenience initializers, for free! 

Optionally, you can also use Swift's `@available` attribute to "deprecate" `init`, which will give a warning if `init` is called directly but not if it's called via a convenience initializer. 😉 

See `EVReflectionCustomInitializer.swift` unit tests for an example.

### CODE REVIEW

**Comment by JRG-Developer** [comment]
@evermeer 

Sorry, there's problems here...

It breaks `AlamofireJsonToObjects`. :(

**Comment by JRG-Developer** [comment]
Sigh, I'm going to look into this, but for now, I'd recommend reverting the merge.

**Comment by evermeer** [comment]
😬Did not test that...

**Comment by JRG-Developer** [comment]
Yeah, Swift is a devil at times to make work with Generics.

I'll try to work magic here and report back...

**Comment by evermeer** [comment]
Now I remember that this was the reason why I made them required...
I'm not sure if there is a workaround for this...

**Comment by evermeer** [comment]
I reverted the change... 

But then it looks like it's not too difficult to change AlamofireJsonToObject so that you don't need the required init.

I replaced the line where the error was with this and that also works:

```
                        let t = T()
                        let jsonDict = EVReflection.dictionaryFromJson(json)
                        EVReflection.setPropertiesfromDictionary(jsonDict, anyObject: t)
                        completionHandler(self.request, self.response, Result.Success(t))
```

That could be good enough... I will do some tests before pushing this...

**Comment by Dimillian** [comment]
I like that change, I had to do some workaround because I couldn't create custom  init

**Comment by evermeer** [comment]
I'm now testing the rest of my code... Also the AlamofireXmlToObjects needed the same change. Will push the change to EVReflection in a moment...

**Comment by evermeer** [comment]
And it's now pushed as version 2.24.0

EVWordpressAPI and AlamofireOauth2 also needed an update (mostly because of Swift 2.2 compatibility issues)

**Comment by JRG-Developer** [comment]
👍 Awesome, thanks!

**Pull request merged**
