### PR TITLE
Bool Type Support

### PR DESCRIPTION
**Pull request by saintevil**
Hi There.

I have been using the library well.
So. Need a 'Bool' type support

Please Check it. Thanks you.

### CODE REVIEW

**Comment by evermeer** [comment]
Hi, As you probably already noticed this did not work. The NSJSONSerialization library from Apple needs data that is convertable to NSObject. It will us a NSNumber for representing a Bool. For this I already have the following code in EVReflection:

```
} else if typeInObject == "NSNumber" && (type == "String" || type == "NSString") {
            if let convertedValue = (value as? String)?.lowercaseString {
                if convertedValue == "true" || convertedValue == "yes" {
                    value = 1
                } else if convertedValue == "false" || convertedValue == "no" {
                    value = 0
                } else {
                    value = NSNumber(double: Double(convertedValue) ?? 0)
                }
            }
```

Not long ago (couple of weeks?) the check for true, yes, false and no was added. Before that only 0 and 1 where supported. 

See: https://github.com/evermeer/EVReflection/issues/102

**Comment by saintevil** [comment]
Okey. It's Optional type.   so 'Incorrect type' error.

**Comment by evermeer** [comment]
If you are using an optional struct like Bool? or Int? then Swift is not able to call the function 'setValue forKey' When running EVReflection you will see a warning like this in the output:

```
WARNING: The class 'XTest' is not key value coding-compliant for the key 'field2'
 There is no support for optional type, array of optionals or enum properties.
As a workaround you can implement the function 'setValue forUndefinedKey' for this. See the unit tests for more information
```

So you could do the following things here:
1. change the property to an optional NSNumber. nil is nil, 0 is false, 1 is true.
2. make the Bool not optional (default value false?)
3. implement the function 'setvalue forUndefinedKey'. For sample code see https://github.com/evermeer/EVReflection/blob/ddb5bc7c754a388745457610a5b087b9ba4d4fec/EVReflection/EVReflectionTests/EVReflectionConversionOptionsTest.swift#L85-L85

**Comment by saintevil** [comment]
Thanks a lot!

**Pull request closed without merging**
